# Generated by Django 5.2.1 on 2025-05-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='student_cards/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('student_card_type', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.CharField(blank=True, max_length=50, null=True)),
                ('student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cohort', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
